### ISSUE TITLE
What kind of segment image should input together with image?

### ISSUE THREAD

**Issue by mychina75** [codeslake/Color_Transfer_Histogram_Analogy#1]
Hi, thank you for your work.
I can not find example to deploy the model. Can you give more infor about the mask image?

**Comment by codeslake** [comment]
Hi, thanks for your interest in our work.

Sorry for the confusion as the codes are not well organized yet.

We used the seg-map as in PNG format image, which is 24bit RGB image.
The code will automatically map the same sematic between the seg-map of input and the target images.

**Comment by mychina75** [comment]
so, the mask image is a semaintic or panoramic segmentation result? how about the classes defined in the segmentaion?
thank you.

**Comment by codeslake** [comment]
Yes, the mask images are the semantic segmented images. The classes defined in image doesn't matter, as long as values are defined the same for both source and target segmentation maps.

I used 24bit RGB image, as in integer value from 0-255.
The semantic replacement module automatically matches the same values (class) between source and target segmentation maps.
