### ISSUE TITLE
When I try to turn on semantic replacement, I met a bug as follows :

### ISSUE THREAD

**Issue by lsfhuihuiff** [codeslake/Color_Transfer_Histogram_Analogy#10]

**Comment by lsfhuihuiff** [comment]
RuntimeError: output with shape[1,1024,768] dosen't match the  broadcast shape[3,1024,768]
I check the segmentation of image is 3 channels. Could you please tell me how I can solve this problem?

**Comment by codeslake** [comment]
Hi, @lsfhuihuiff.

Where exactly does the error occur?

**Comment by codeslake** [comment]
Hi, @lsfhuihuiff.

I am closing the issue as it has been a week since my last comment.
Please reopen this issue if you still have a problem!

**Comment by lsfhuihuiff** [comment]
Dear JunyongLee，

 Thank you for your reply. I'm sorry I didn't check my messages in time.
 In fact ,I do not know how to join the segmentation image module.Are there some specific requirements for image segmentation?
 It would be great if you would like to enrich the use of this section in the Readme section .

 Thank you very much！
Have a good day!
Sifei Li

发件人：Junyong Lee ***@***.***>
发送日期：2021-12-09 22:24:52
收件人：codeslake/Color_Transfer_Histogram_Analogy ***@***.***>
抄送人：lsfhuihuiff ***@***.***>,Mention ***@***.***>
主题：Re: [codeslake/Color_Transfer_Histogram_Analogy] When I try to turn on semantic replacement, I met a bug as follows : (Issue #10)

Hi, @lsfhuihuiff.
Where exactly does the error occur?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by codeslake** [comment]
Hi, @lsfhuihuiff.

You may refer [here](https://github.com/codeslake/Color_Transfer_Histogram_Analogy/issues/8#issuecomment-916795101) for more details about the segmentation map.

Best,
