### ISSUE TITLE
running on cpu

### ISSUE THREAD

**Issue by yarinlevy1018** [codeslake/Color_Transfer_Histogram_Analogy#14]
hi, can I run this code on CPU only? if the answer is yes, where I should need to change the code? because my computer doesn't have a GPU device, and the code is failing...

**Comment by codeslake** [comment]
It is not currently supported.
You can change every line with `.cuda()` or `.to('cuda')` to `.to('cpu')`.
I will try to add CPU availability in my spare time (probably next week).

**Comment by yarinlevy1018** [comment]
thanks you so much! and thanks for your code!

‫בתאריך יום ה׳, 25 באוג׳ 2022 ב-3:35 מאת ‪Junyong Lee‬‏ <‪
***@***.***‬‏>:‬

**Comment by yarinlevy1018** [comment]
hi, can you please publish a version which supported cpu?
I'v tried to change the code as you've written but I still get errors of fork and multi-proccessing...

**Comment by codeslake** [comment]
Hi,  I will be able to work on it probably next week.

**Comment by codeslake** [comment]
Sorry for the delay, refer [here](https://github.com/codeslake/Color_Transfer_Histogram_Analogy/issues/16#issuecomment-1330962921), please.
