### ISSUE TITLE
Can the author publish the files for network training, there are only test codes on Git

### ISSUE THREAD

**Issue by zhanghongwei** [codeslake/Color_Transfer_Histogram_Analogy#15]
Looking forwarnd to try the trainning

**Comment by Wp-Zhang** [comment]
Hi, I'm also trying to train the model from scratch. Do you mind sharing the code for training? Thanks!

**Comment by codeslake** [comment]
Refer [here](https://github.com/codeslake/Color_Transfer_Histogram_Analogy/issues/16#issuecomment-1330962921), thanks!
