### ISSUE TITLE
Windows : Error num_worker > 0

### ISSUE THREAD

**Issue by crenaudineau1** [codeslake/Color_Transfer_Histogram_Analogy#4]
Hello,

I am on Windows, python 3.8.8, pytorch 1.8.0 and cuda 10.2.

I need to fix num workers to 0 in dataloader (customdataset) for a working code but it is very slow. If I let num_workers > 0 I have a error.

I have update test.py with :

if __name__ == '__main__':
    test()

But the problem persists. Someone have fix this issue on Windows ? How ?

Thanks a lot.

**Comment by codeslake** [comment]
I've never tried this code (actually non of deep learning codes..) in Windows.
Please let me know if you find a solution!

Thanks
