### ISSUE TITLE
No such file or directory: 'CHECKPOINT_ROOT\\latest_net_G_A.pth'

### ISSUE THREAD

**Issue by Mrchenuo** [codeslake/Color_Transfer_Histogram_Analogy#5]
Hi, thanks for your great work. But when I run the code, I encountered an error, and the output is as follows :
No such file or directory: 'CHECKPOINT_ROOT\\latest_net_G_A.pth'
But the checkpoints folder you provided only includes IFAN.pytorch, IFAN_8.pytorch, IFAN_16bit.pytorch, IFAN_26.pytorch, IFAN_35.pytorch, IFAN_44.pytorch, IFAN_dual.pytorch. And I don’t know the meaning of these files. So I want to ask you how to solve this problem, thank you very much.

**Comment by codeslake** [comment]
Hi, thanks for pointing it out!
I've just updated the download link.
Would you check the link again?

Thanks

**Comment by Mrchenuo** [comment]
Hi,Thank you for updating the download link. 
I just re-downloaded checkpoints and the code has run successfully.（＾∀＾●）ﾉｼ
