### ISSUE TITLE
Examples of input masks

### ISSUE THREAD

**Issue by mnbrshd** [codeslake/Color_Transfer_Histogram_Analogy#8]
Hello,

I have been trying to use your repo and want to generate my own data for testing. Can you please provide a few examples of what the masks for the images are supposed to look like? I couldn't understand that from your paper.

Thanks.

**Comment by codeslake** [comment]
Hi, @mnbrshd. 

If you are asking visual appearance of a segmentation map, it should look like the ones that are in [this link](https://www.jeremyjordan.me/evaluating-image-segmentation-models/).
You can use any public segmentation method on images that you wanna test. (We used [this method](https://ieeexplore.ieee.org/abstract/document/8006236) for our paper.) 

If you are talking about the specification of a segmentation map, I used a 24bit RGB image, as in integer value ranged in 0-255.

Best,

**Comment by mnbrshd** [comment]
Thank you!
